repos:
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.5.3
  hooks:
   - id: nbqa-black
     args: [--check]
     additional_dependencies: [black==22.10.0]
   - id: nbqa-flake8
     additional_dependencies: [flake8==6.0.0]
